apiVersion: apps/v1
kind: Deployment
metadata:
  name: adey-security-service
spec:
  replicas: 1  # Number of app instances to run
  selector:
    matchLabels:
      app: adey-security-service
  template:
    metadata:
      labels:
        app: adey-security-service
    spec:
      containers:
        - name: adey-security-service
          image: us-docker.pkg.dev/marine-defender-459202-r5/adey-security-service/adey-security-service:latest  # Replace with your Docker image
          ports:
            - containerPort: 8080  # Spring Boot default port
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"