apiVersion: v1
kind: Service
metadata:
  name: adey-security-service
spec:
  selector:
    app: adey-security-service  # This should match the app label in the Deployment
  ports:
    - protocol: TCP
      port: 80            # Port to access the service on
      targetPort: 8080     # Port your container is listening on
  type: LoadBalancer      # Exposes the app to the internet (optional)