name: Deploy Spring Boot JAR to Debian Docker Host

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy JAR to remote host
      run: |
        scp -o StrictHostKeyChecking=no target/your-app.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/home/${{ secrets.REMOTE_USER }}/your-app.jar

    - name: Deploy via SSH
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
          docker stop myapp || true
          docker rm myapp || true
          docker rmi myapp:latest || true
          cd /home/${{ secrets.REMOTE_USER }}
          docker build -t myapp:latest .
          docker run -d -p 8080:8080 --name myapp myapp:latest
        EOF
