name: Build and Deploy Spring Boot App to Remote Debian Docker Host

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: |
        cd adey-security
        mvn clean package -DskipTests

    - name: Set up SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy JAR to Remote Host
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no adey-security/target/*.jar ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:app.jar

    - name: Deploy on Remote Host
      run: |
        ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }} << 'EOF'
        docker stop myapp || true
        docker rm myapp || true
        docker rmi myapp:latest || true

        cat > Dockerfile <<EOL
        FROM openjdk:17-jdk-slim
        COPY app.jar app.jar
        ENTRYPOINT ["java", "-jar", "/app.jar"]
        EOL

        docker build -t myapp:latest .
        docker run -d -p 8080:8080 --name myapp myapp:latest
        EOF
